// <auto-generated />
using System;
using DataAccessLayer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EntityLayer.Entities.RequestLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HttpMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogLevel")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("QueryString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StackTrace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("StatusCode");

                    b.ToTable("RequestLogs");
                });

            modelBuilder.Entity("EntityLayer.Entities.StockItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cabinet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CriticalQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Shelf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StockClass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StockUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StockUnitId");

                    b.ToTable("StockItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bbbbbbbb-0000-0000-0000-000000000001"),
                            Cabinet = "D-01",
                            CreatedDate = new DateTime(2025, 12, 17, 9, 56, 24, 642, DateTimeKind.Utc).AddTicks(3772),
                            CriticalQuantity = 100.00m,
                            IsActive = true,
                            Quantity = 1232257.99m,
                            Shelf = "A-01",
                            StockClass = "RawMaterial",
                            StockUnitId = new Guid("aaaaaaaa-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-0000-0000-0000-000000000002"),
                            Cabinet = "D-01",
                            CreatedDate = new DateTime(2025, 12, 17, 9, 56, 24, 642, DateTimeKind.Utc).AddTicks(3774),
                            CriticalQuantity = 0.00m,
                            IsActive = true,
                            Quantity = 500.00m,
                            Shelf = "A-02",
                            StockClass = "RawMaterial",
                            StockUnitId = new Guid("aaaaaaaa-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-0000-0000-0000-000000000003"),
                            Cabinet = "D-02",
                            CreatedDate = new DateTime(2025, 12, 17, 9, 56, 24, 642, DateTimeKind.Utc).AddTicks(3775),
                            CriticalQuantity = 0.00m,
                            IsActive = true,
                            Quantity = 508.00m,
                            Shelf = "A-02",
                            StockClass = "RawMaterial",
                            StockUnitId = new Guid("aaaaaaaa-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-0000-0000-0000-000000000004"),
                            Cabinet = "D-02",
                            CreatedDate = new DateTime(2025, 12, 17, 9, 56, 24, 642, DateTimeKind.Utc).AddTicks(3777),
                            CriticalQuantity = 0.00m,
                            IsActive = true,
                            Quantity = 15.00m,
                            Shelf = "B-01",
                            StockClass = "RawMaterial",
                            StockUnitId = new Guid("aaaaaaaa-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-0000-0000-0000-000000000005"),
                            Cabinet = "D-03",
                            CreatedDate = new DateTime(2025, 12, 17, 9, 56, 24, 642, DateTimeKind.Utc).AddTicks(3778),
                            CriticalQuantity = 0.00m,
                            IsActive = true,
                            Quantity = 49.00m,
                            Shelf = "B-01",
                            StockClass = "RawMaterial",
                            StockUnitId = new Guid("aaaaaaaa-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-0000-0000-0000-000000000006"),
                            Cabinet = "D-03",
                            CreatedDate = new DateTime(2025, 12, 17, 9, 56, 24, 642, DateTimeKind.Utc).AddTicks(3780),
                            CriticalQuantity = 20.00m,
                            IsActive = true,
                            Quantity = 104891966.00m,
                            Shelf = "B-02",
                            StockClass = "RawMaterial",
                            StockUnitId = new Guid("aaaaaaaa-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-0000-0000-0000-000000000007"),
                            Cabinet = "D-03",
                            CreatedDate = new DateTime(2025, 12, 17, 9, 56, 24, 642, DateTimeKind.Utc).AddTicks(3781),
                            CriticalQuantity = 1000.00m,
                            IsActive = true,
                            Quantity = 10000.00m,
                            Shelf = "C-01",
                            StockClass = "RawMaterial",
                            StockUnitId = new Guid("aaaaaaaa-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-0000-0000-0000-000000000008"),
                            Cabinet = "D-04",
                            CreatedDate = new DateTime(2025, 12, 17, 9, 56, 24, 642, DateTimeKind.Utc).AddTicks(3782),
                            CriticalQuantity = 5.00m,
                            IsActive = true,
                            Quantity = 10.00m,
                            Shelf = "C-01",
                            StockClass = "RawMaterial",
                            StockUnitId = new Guid("aaaaaaaa-0000-0000-0000-00000000000a")
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-0000-0000-0000-000000000009"),
                            Cabinet = "D-04",
                            CreatedDate = new DateTime(2025, 12, 17, 9, 56, 24, 642, DateTimeKind.Utc).AddTicks(3784),
                            CriticalQuantity = 1.00m,
                            IsActive = true,
                            Quantity = 124719.00m,
                            Shelf = "C-02",
                            StockClass = "RawMaterial",
                            StockUnitId = new Guid("aaaaaaaa-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-0000-0000-0000-00000000000a"),
                            Cabinet = "D-05",
                            CreatedDate = new DateTime(2025, 12, 17, 9, 56, 24, 642, DateTimeKind.Utc).AddTicks(3785),
                            CriticalQuantity = 0.00m,
                            IsActive = true,
                            Quantity = 5451.00m,
                            Shelf = "D-01",
                            StockClass = "RawMaterial",
                            StockUnitId = new Guid("aaaaaaaa-0000-0000-0000-000000000002")
                        });
                });

            modelBuilder.Entity("EntityLayer.Entities.StockType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("StockTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedDate = new DateTime(2025, 12, 17, 9, 56, 24, 642, DateTimeKind.Utc).AddTicks(3600),
                            IsActive = true,
                            Name = "Kağıt"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedDate = new DateTime(2025, 12, 17, 9, 56, 24, 642, DateTimeKind.Utc).AddTicks(3604),
                            IsActive = true,
                            Name = "Zarf"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedDate = new DateTime(2025, 12, 17, 9, 56, 24, 642, DateTimeKind.Utc).AddTicks(3604),
                            IsActive = true,
                            Name = "Zımba"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedDate = new DateTime(2025, 12, 17, 9, 56, 24, 642, DateTimeKind.Utc).AddTicks(3605),
                            IsActive = true,
                            Name = "Toner"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedDate = new DateTime(2025, 12, 17, 9, 56, 24, 642, DateTimeKind.Utc).AddTicks(3606),
                            IsActive = true,
                            Name = "Bant"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            CreatedDate = new DateTime(2025, 12, 17, 9, 56, 24, 642, DateTimeKind.Utc).AddTicks(3607),
                            IsActive = true,
                            Name = "Karton"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            CreatedDate = new DateTime(2025, 12, 17, 9, 56, 24, 642, DateTimeKind.Utc).AddTicks(3607),
                            IsActive = true,
                            Name = "Folyo"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            CreatedDate = new DateTime(2025, 12, 17, 9, 56, 24, 642, DateTimeKind.Utc).AddTicks(3609),
                            IsActive = true,
                            Name = "Forex"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            CreatedDate = new DateTime(2025, 12, 17, 9, 56, 24, 642, DateTimeKind.Utc).AddTicks(3609),
                            IsActive = true,
                            Name = "Bitmiş Ürün"
                        });
                });

            modelBuilder.Entity("StockUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BuyingCurrency")
                        .HasColumnType("int");

                    b.Property<decimal>("BuyingPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("PaperWeight")
                        .HasColumnType("int");

                    b.Property<int>("QuantityUnit")
                        .HasColumnType("int");

                    b.Property<int>("SellingCurrency")
                        .HasColumnType("int");

                    b.Property<decimal>("SellingPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("StockTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("StockTypeId");

                    b.ToTable("StockUnits");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000001"),
                            BuyingCurrency = 0,
                            BuyingPrice = 0.00m,
                            Code = "8544545",
                            CreatedDate = new DateTime(2025, 12, 17, 9, 56, 24, 642, DateTimeKind.Utc).AddTicks(3733),
                            IsActive = true,
                            QuantityUnit = 4,
                            SellingCurrency = 0,
                            SellingPrice = 0.00m,
                            StockTypeId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000002"),
                            BuyingCurrency = 0,
                            BuyingPrice = 400.00m,
                            Code = "2434536436",
                            CreatedDate = new DateTime(2025, 12, 17, 9, 56, 24, 642, DateTimeKind.Utc).AddTicks(3739),
                            Description = "Jnyfyv",
                            IsActive = true,
                            PaperWeight = 100,
                            QuantityUnit = 1,
                            SellingCurrency = 0,
                            SellingPrice = 700.00m,
                            StockTypeId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000003"),
                            BuyingCurrency = 0,
                            BuyingPrice = 0.00m,
                            Code = "12345678906",
                            CreatedDate = new DateTime(2025, 12, 17, 9, 56, 24, 642, DateTimeKind.Utc).AddTicks(3742),
                            Description = "TEST",
                            IsActive = true,
                            PaperWeight = 0,
                            QuantityUnit = 0,
                            SellingCurrency = 0,
                            SellingPrice = 0.00m,
                            StockTypeId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000004"),
                            BuyingCurrency = 0,
                            BuyingPrice = 0m,
                            Code = "744953400",
                            CreatedDate = new DateTime(2025, 12, 17, 9, 56, 24, 642, DateTimeKind.Utc).AddTicks(3743),
                            Description = "744953400E",
                            IsActive = true,
                            PaperWeight = 0,
                            QuantityUnit = 0,
                            SellingCurrency = 0,
                            SellingPrice = 0m,
                            StockTypeId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000005"),
                            BuyingCurrency = 0,
                            BuyingPrice = 0m,
                            Code = "747223200",
                            CreatedDate = new DateTime(2025, 12, 17, 9, 56, 24, 642, DateTimeKind.Utc).AddTicks(3746),
                            Description = "747223200E",
                            IsActive = true,
                            PaperWeight = 0,
                            QuantityUnit = 0,
                            SellingCurrency = 0,
                            SellingPrice = 0m,
                            StockTypeId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000006"),
                            BuyingCurrency = 0,
                            BuyingPrice = 0m,
                            Code = "748273300",
                            CreatedDate = new DateTime(2025, 12, 17, 9, 56, 24, 642, DateTimeKind.Utc).AddTicks(3747),
                            Description = "748273300E",
                            IsActive = true,
                            PaperWeight = 0,
                            QuantityUnit = 0,
                            SellingCurrency = 0,
                            SellingPrice = 0m,
                            StockTypeId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000007"),
                            BuyingCurrency = 0,
                            BuyingPrice = 0m,
                            Code = "750221650",
                            CreatedDate = new DateTime(2025, 12, 17, 9, 56, 24, 642, DateTimeKind.Utc).AddTicks(3749),
                            Description = "750221650E",
                            IsActive = true,
                            PaperWeight = 0,
                            QuantityUnit = 0,
                            SellingCurrency = 0,
                            SellingPrice = 0m,
                            StockTypeId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000008"),
                            BuyingCurrency = 0,
                            BuyingPrice = 0m,
                            Code = "750223600",
                            CreatedDate = new DateTime(2025, 12, 17, 9, 56, 24, 642, DateTimeKind.Utc).AddTicks(3750),
                            Description = "750223600E",
                            IsActive = true,
                            PaperWeight = 0,
                            QuantityUnit = 0,
                            SellingCurrency = 0,
                            SellingPrice = 0m,
                            StockTypeId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000009"),
                            BuyingCurrency = 0,
                            BuyingPrice = 0m,
                            Code = "7248273300",
                            CreatedDate = new DateTime(2025, 12, 17, 9, 56, 24, 642, DateTimeKind.Utc).AddTicks(3752),
                            Description = "7248273300E",
                            IsActive = true,
                            PaperWeight = 0,
                            QuantityUnit = 0,
                            SellingCurrency = 0,
                            SellingPrice = 0m,
                            StockTypeId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-00000000000a"),
                            BuyingCurrency = 0,
                            BuyingPrice = 0m,
                            Code = "7250222500",
                            CreatedDate = new DateTime(2025, 12, 17, 9, 56, 24, 642, DateTimeKind.Utc).AddTicks(3753),
                            Description = "7250222500E",
                            IsActive = true,
                            PaperWeight = 0,
                            QuantityUnit = 0,
                            SellingCurrency = 0,
                            SellingPrice = 0m,
                            StockTypeId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("EntityLayer.Entities.StockItem", b =>
                {
                    b.HasOne("StockUnit", "StockUnit")
                        .WithMany("StockItems")
                        .HasForeignKey("StockUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StockUnit");
                });

            modelBuilder.Entity("StockUnit", b =>
                {
                    b.HasOne("EntityLayer.Entities.StockType", "StockType")
                        .WithMany("StockUnits")
                        .HasForeignKey("StockTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StockType");
                });

            modelBuilder.Entity("EntityLayer.Entities.StockType", b =>
                {
                    b.Navigation("StockUnits");
                });

            modelBuilder.Entity("StockUnit", b =>
                {
                    b.Navigation("StockItems");
                });
#pragma warning restore 612, 618
        }
    }
}
